spring:
  application:
    name: admin-service




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://edb-server.herokuapp.com/eureka/
  instance:
    preferIpAddress: true
