spring:
  application:
    name: admin-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/YounessBouhjar/EDB-ConfigServ
          default-label: main
          clone-on-start: true
          force-pull: true
          searchPaths: myapp


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://edb-server.herokuapp.com/eureka
  instance:
    preferIpAddress: true
